### ISSUE TITLE
Widen this to not just the USA 

### ISSUE THREAD

**Issue by kilasuit** [2020PB/police-brutality#416] opened 2020-06-07 22:30 UTC
Police brutality occurs in many other countries too.

Therefore I ask you recognise this with allowing non USA entries and suggest that you add Country to your Report Issue Template for completeness

**Comment by ZenPylon** [comment] 2020-06-08 13:30
Thanks for opening this, @kilasuit .  I'm inclined to agree with this, especially given the sustained volume of reports we've had.  

I'm also wondering about the timeframe as well.  How might this repo function when the immediacy of George Floyd protests is no longer the target of police brutality.  In other words, as police brutality continues into the future beyond the scope of George Floyd's murder, how do we want to continue efforts?

One idea would be to make this repo specific to George Floyd protests.  Another would be to work on a more robust method of curating and filtering reports based on time, location, and other factors, so that George Floyd-specific reports can easily be identified from a broader set of compiled evidence (if needed).

**Comment by haydenbspence** [comment] 2020-06-08 23:15
@ZenPylon 

I would be interested in broadening it beyond the time frame of the present protests as well as internationally. However, we may keep parameters that incidents must be related to domestic policing and not include incidents of violence outside, the umbrella can get fairly large if we don't set good parameters of what we are collecting here.

I have an MS in Prevention Science. I would suspect this kind of archive/dataset would be useful for many looking at police reform, violence prevention, and beyond the realm of journalism and prosecution as we have set our aim towards. There are other organizations that do this as well, and it would be important we don't duplicate efforts and try and fill a niche of what we don't see already being done.

**Comment by 01210210** [comment] 2020-06-09 13:20
I think widening beyond the US in the same repo is a bad idea at this point in time. It is already going to be a huge challenge to stay on top of what's here and make sure people are held accountable based on their city/state's laws and policies. Adding other countries will add a layer of complexity (more languages, different police systems, do you include military abuse? do you include internment camps like those in Xinjiang?) that is better achieved by forking and starting country or region specific projects. Those forks can also be easily aggregated in a single repo if we really need a single centralized database that's international.

**Comment by ZenPylon** [comment] 2020-06-09 14:11
@01210210 Thanks for your thoughtful response.  That's a good point - we can always aggregate this at a later date if needed.  Given the resources to needed to manage submissions and the nuances required to discern what is an appropriate match for this repo, I think we can close this issue.  

We can open a new issue if this becomes relevant at a later point in time.

**Comment by ubershmekel** [comment] 2020-06-09 18:58
This isn't the first request we've gotten for adding international data. One approach would be to make another repo and data pipeline that's open to international data. The challenge is getting people to populate it. The more diffused the problem is, the more unrelated the datapoints are, the harder it is to motivate people to maintain it. That's part of why we're sticking to this very specific, urgently needed, scope. But I would urge and celebrate an international fork.

**Comment by ubershmekel** [comment] 2020-07-02 00:45
Closing this for now. If someone ends up forking, please add a comment to this issue with the link.

**Closed by ubershmekel** 2020-07-02 00:45 UTC
